version: '3'
services:
  database:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=asdf
    ports:
      - "5432:5432"
    # volumes:
    #   - ./schema.sql:/docker-entrypoint-initdb.d/schema_0.sql
    command: postgres -c 'max_wal_size=2GB'
